### ISSUE TITLE
clock configuration

### ISSUE THREAD

**Issue by luggi** [silver13/h8mini-testing#1]
are you sure the clock configuration is correct ?
to me it seems that the GD32F130G6 should run at 48 MHz according to the Datasheet 
and from the pwm driver it seems as if the peripheral clock running at ~4 mhz (490*8192)? shouldn't that be the same as the system clock ?

**Comment by silver13** [comment]
thank you, you are right, the clock is not correct
i'll fix it sometime soon but it will require some testing since all the other clocks will be different so it might be a couple of days till it makes it on github
