### ISSUE TITLE
flips without throttle

### ISSUE THREAD

**Issue by Haxk20** [silver13/h8mini-testing#11]
Hi as title says i need to flip the quad without throttle but its imposible now is there any way to do that i really need it for tricks

**Comment by Haxk20** [comment]
Not automatic flils but like manual well better said i need to have control of the quad like to get it forward back left right with 0 throttle i think you know what i mean is there any way to do that ?

**Comment by silver13** [comment]
in acro or level?

in acro, the option "#define ENABLESTIX 1" will help when the sticks are not centered ( during flips)

**Comment by Haxk20** [comment]
In acro but i mean i want to have control like when i increase throttle quad goes up and then i can control it forward and like fly with it but i want to do that but i need to control it like that with 0 throttle.

**Comment by Haxk20** [comment]
I want control of the quad like in the air but 0 throttle.

**Comment by hgoblin91** [comment]
good, thanks for your good work. my question is if you can put the quad in both h8 airmode mode and H101. and I would also like to know if you offer them support eachine E010 board as these are difficult to adapt to this model by its form in X. greetings and thanks

**Comment by Haxk20** [comment]
Thanks very much helped a lot.
