### ISSUE TITLE
Airmode

### ISSUE THREAD

**Issue by hgoblin91** [silver13/h8mini-testing#12]
Good, thanks for your good work. my question is if you can put the quad in both h8 airmode mode and H101. and I would also like to know if you offer them support eachine E010 board as these are difficult to adapt to this model by its form in X. greetings and thanks

**Comment by silver13** [comment]
Hi, there is an option "#define ENABLESTIX 1" which enables the motors when throttle is zero, and one other stick is not centered.

The  eachine E010 is not supported, if you want to install a board from H8 or H101 it is possible to do that.
Please ask in the rcgroups thread for instructions http://www.rcgroups.com/forums/showthread.php?t=2512604

**Comment by Haxk20** [comment]
Hi i dont wanna to make another issue but i wanna to trim the quad like bypass the gyro to think its flat but rotated in one direction is that possible to make that in code ?

**Comment by Haxk20** [comment]
or better say i need to add some more power to one motor  but leave other normal is that possible ?
