### ISSUE TITLE
one motor is slow

### ISSUE THREAD

**Issue by Haxk20** [silver13/h8mini-testing#13]
First its not motor fault it must be in code but i need to make one motor little bit faster then others is that possible somehow ?

**Comment by silver13** [comment]
I fixed a bug today, related to drifts , I think your problem might be fixed now

**Comment by Haxk20** [comment]
yeahhhhhhhhhh thanksssssssssssssss woooow now i have fully functional quad woooow and one question is there way to make airmode rotation a lot faster since when i wanna to do a flip its rotating so slow with 0 throttle it crash all the time when i do flip with 0 TH so how to make it lot faster ?

**Comment by silver13** [comment]
Sorry, there is no easy way apart from increasing the rates and maybe pids
