### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by Haxk20** [silver13/h8mini-testing#14]
I dont like to open new issue when i have a question so i decided to just make this.
my question what ENABLESTIX_TRESHOLD do when i change it up because i want ENABLESTIX a lot faster because its slow for me so im asking you Thanks

**Comment by Haxk20** [comment]
And before you say its not easy but at least tell what numbers change or whatever or you can make the enablestix like 3or 4 times faster

**Comment by silver13** [comment]
the problem is I really do not know how to help you.

If I could make it faster, I would do it, I don't slow down a feature or something like that. Enablestix is a feature that turns on the motors at zero throttle. If the quad turns slower, what can I do?

**Comment by Haxk20** [comment]
So there is no way to make enablestix to rotate faster i mean rotate i n roll faster ? Well thats bad because i cannot do manual flips then i think its time for custom build quad but please leave thiss issue open because its for questions

**Comment by Haxk20** [comment]
i think what may be possible is to make motors sin faster in enablestix if this is possible

**Comment by silver13** [comment]
if you want the motors to spin faster, add more throttle, then there is no need for ENABLESTIX in the first place

**Comment by Haxk20** [comment]
I want to rotate quad in the air with 0 throttle then you said me to enablestix yes its working but when i wanna to rotate the quad its going slow and when i watch videos they can do roll with 0 throttle 20 cm off ground but i need to be 5 meters in air to not crash because its rotating slow

**Comment by Haxk20** [comment]
i just saw that when im in acro pro mode the enablestix is fast now but its impossible for me to control the quad in pro mode with stock controller so im thinking about building my own quad but its expensive like a lot but what ever its time to make step forward i think first i need to make some money

**Comment by silver13** [comment]
Hi, I doubt you saw a video of a brushed quad doing a flip at 20 cm off the ground.

Some quadcopters have a lot of thrust, and there is a reason there are $20 quads and $2000. You can't expect the cheapest quad around to beat brushless quads worth at least 10 times as much.

**Comment by Haxk20** [comment]
Ouuu yeah so i need brushed quad ? Its expensive motors (10$ piece) for 150 frame and ESC (10$piece) too but i think i can make that money with KISSFC i think it will be good but is there some cheap TX (i mean the thing with you can control quad dont know how its called in english)

**Comment by Haxk20** [comment]
One little question which file send ble packets ? I mean the battery mAh ?

**Comment by silver13** [comment]
the ble packets are sent from file rx_bayang_protocol.c

**Comment by Haxk20** [comment]
And which command send the battery voltage ?

**Comment by silver13** [comment]
This is not one question, it's a lot. The purpose of github issues is to improve the code. I don't have time to answer basic programming questions.

Please read a programming tutorial if you wish to understand it. I am not a programming tutor, nor is this the place for such questions.
