### ISSUE TITLE
Directly toggle headless instead of with stick gestures? 

### ISSUE THREAD

**Issue by bombarie** [silver13/h8mini-testing#6]
First off, thanks for this firmware! So cool to toy around with the h8's behavior like this. 

I've added some new stick gestures to the firmware to turn headless mode on and off but was wondering if there's a direct way to do it which takes less time. I'm sending the stick gestures through and arduino imposing an artificial delay between each stick direction. It would be great to trigger things in one go. Maybe by using a trim?

**Comment by silver13** [comment]
What transmitter are you using, stock?

**Comment by bombarie** [comment]
Not the stock tx. I'm using an NRF24L01 transceiver and a modified version of the nrf24_multipro library (https://github.com/goebish/nrf24_multipro). It's all on the Arduino. I'm feeding throttle/yaw/pitch/roll values to the Arduino from my computer.

**Comment by silver13** [comment]
The protocol in multipro sends headless, "return home" and flip (3 channels) , should be enough for headless, right? The trims are coded in multipro to a percentage of actual controls, to increase maximum control range for the stock firmware.

if you disable this feature of the trims, you could use the trims as control channels

**Comment by bombarie** [comment]
wonderful! I'll try that out. Thanks for the swift replies
