### ISSUE TITLE
quad going to one direction

### ISSUE THREAD

**Issue by Haxk20** [silver13/h8mini-testing#9]
I buyed new quad flash that firmware everything is ok but the quad is going back left in acro and in level mode when quad is horizontal back left motor not spinning but when i rotate quad in that direction motor normally start to spin i dont think its motor problem i think there is something whit the code HELP

**Comment by Haxk20** [comment]
I can control it normally but still going to back left when i leave it in air its rotate to back left and crashes

**Comment by silver13** [comment]
Can you ask this in the forum please, I can't respond across a lot of websites, I only have so much time

**Comment by Haxk20** [comment]
Buying new quad closing
